version: '3'

services:
  backend:
    container_name: backend
    image: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./frontend/etc/nginx/ssl:/frontend/etc/nginx/ssl # Access frontend's files, including SSL certs
    env_file:
      - .env
    # networks:
    #   - ft_transcendence

  ponggame:
    container_name: ponggame
    image: ponggame
    build: ./PongGame
    ports:
      - "5050:5050"
    volumes:
      - ./PongGame:/app

  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    ports:
      - "3000:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./backend/media/images:/usr/share/nginx/html/media/images

