
version: '3'

volumes:
  transcendance:
    driver: local
    driver_opts:
      type: none
      device: /home/ahbajaou/Desktop/befro_merge/frontend
      o: bind

  back:
    driver: local
    driver_opts:
      type: none
      device: /home/ahbajaou/Desktop/befro_merge/backend
      o: bind

services:
  backend:
    container_name: backend
    image: backend
    build: ./backend
    ports:
      - "8000:8000"
    # networks:
    #   - ft_transcendence
  
  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - transcendance:/usr/share/nginx/html
      - back:/backend

    # networks:
    #   ft_transcendence:
    #     driver: bridge
  # game:
  #   container_name: game
  #   image: game
  #   build: ./game
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - ft_transcendence
  # chat:
  #   container_name: chat
  #   image: chat
  #   build: ./chat
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - ft_transcendence
