
services:

  postgree_db:
    image: postgres:15
    container_name: postgree_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    restart: always
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  backend:
    depends_on:
      - postgree_db
    container_name: backend
    image: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env

  

  ponggame:
    container_name: ponggame
    image: ponggame
    build: ./PongGame
    ports:
      - "5050:5050"
    volumes:
      - ./PongGame:/app

  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    ports:
      - "3000:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./backend/media/images:/usr/share/nginx/html/media/images


  blockchain:
    build: ./blockchain
    ports:
      - "8545:8545" 
    volumes:
      - ./blockchain:/usr/src/app 

  tictactoe:
    container_name: tictactoe
    image: tictactoe
    build: ./TicTacToe
    # ports:
    #   - "4040:4040"
    volumes:
      - ./TicTacToe:/app
  
  
volumes:
  postgres_data: